version: '3.8'
name: huntit

services:
  backend-database:
    image: postgres:16
    container_name: backend-database
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ../volumes/huntit/backend-database:/var/lib/postgresql/data
    ports:
      - 5430:${DATABASE_PORT}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME} > /dev/null || exit 1']
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - huniit_network

  api-service:
    container_name: api-service
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        - NODE_VERSION=${NODE_VERSION}
    working_dir: /srv
    volumes:
      - ./:/srv
    depends_on:
      - backend-database
      - jaeger
    ports:
      - 9229:9299
      - 3000:3000
    environment:
      - FORCE_COLOR=1
    networks:
      - huniit_network
    mem_limit: 4096MB

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - 16686:16686
      - 4317:4317
      - 4318:4318
    environment:
      - LOG_LEVEL=debug
    networks:
      - huniit_network

networks:
  huniit_network:
    driver: bridge

volumes:
  dev-postgres-data:
    external: true
