module.exports = {
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: '../',
  testEnvironment: 'node',
  runtime: '@side/jest-runtime',
  transform: {
    '^.+\\.(t|j)s$': '@swc/jest',
  },
  setupFiles: ['./jest/setup-tests.ts'],
  moduleNameMapper: {
    '@core/common/base-http-client/(.*)': '<rootDir>/libs/base-http-client/src/$1',
    '@core/common/base-http-client': '<rootDir>/libs/base-http-client/src',
    '@core/common/common/(.*)': '<rootDir>/libs/common/src/$1',
    '@core/common/common': '<rootDir>/libs/common/src',
    '@core/common/ddd/(.*)': '<rootDir>/libs/ddd/src/$1',
    '@core/common/ddd': '<rootDir>/libs/ddd/src',
    '@core/common/cqrs/(.*)': '<rootDir>/libs/cqrs/src/$1',
    '@core/common/cqrs': '<rootDir>/libs/cqrs/src',
    '@core/common/graphile-worker/(.*)': '<rootDir>/libs/graphile-worker/src/$1',
    '@core/common/graphile-worker': '<rootDir>/libs/graphile-worker/src',
    '@core/common/oauth-authorization/(.*)': '<rootDir>/libs/oauth-authorization/src/$1',
    '@core/common/oauth-authorization': '<rootDir>/libs/oauth-authorization/src',
    '@core/common/openapi-decorators/(.*)': '<rootDir>/libs/openapi-decorators/src/$1',
    '@core/common/openapi-decorators': '<rootDir>/libs/openapi-decorators/src',
    '@core/common/testing/(.*)': '<rootDir>/libs/testing/src/$1',
    '@core/common/testing': '<rootDir>/libs/testing/src',
    '@core/common/caching/(.*)': '<rootDir>/libs/caching/src/$1',
    '@core/common/caching': '<rootDir>/libs/caching/src',
  },
};
